### ISSUE TITLE
Infografía U1

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-1-infografia-ToniDepp#2]
[INFOGRAFÍA-EDUARDO-TOMAS-5US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-ToniDepp/files/12482154/INFOGRAFIA-EDUARDO-TOMAS-5US.pdf)

**Comment by MAB288** [comment]
14/20

**Comment by josealfredo79** [comment]
Revisado...
